version: '3.8'

services:
  # Neon Local proxy service
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: acquisitions-neon-local
    ports:
      - '5432:5432'
    environment:
      NEON_API_KEY: ${NEON_API_KEY}
      NEON_PROJECT_ID: ${NEON_PROJECT_ID}
      PARENT_BRANCH_ID: ${PARENT_BRANCH_ID}
      DELETE_BRANCH: 'true' # Creates ephemeral branches for development
    volumes:
      # Persist Neon Local metadata
      - ./.neon_local/:/tmp/.neon_local
      # Git integration for branch detection
      - ./.git/HEAD:/tmp/.git/HEAD:ro
    healthcheck:
      test: ['CMD', 'pg_isready', '-h', 'localhost', '-p', '5432', '-U', 'neon']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: acquisitions-api-dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://neon:npg@neon-local:5432/main?sslmode=require
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET:-dev_jwt_secret_change_in_production}
      LOG_LEVEL: debug
    volumes:
      # Mount source code for development with hot reload
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
    depends_on:
      neon-local:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000/health',
          '||',
          'exit',
          '1',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  default:
    name: acquisitions-dev-network
